### ISSUE TITLE
feat:Interface GP2Y0A21 and HC-SR04 on PACU

### ISSUE THREAD

**Issue by simpleis6est** [Intel-Edge-AI-SW-Developers-2nd-Platoon/platooning_bando_truck_999#16]
Details:
1.Target board: STM32F429ZI
2.Hardware setting (GP2Y0A21)
![ir센서](https://github.com/Intel-Edge-AI-SW-Developers-2nd-Platoon/platooning_bando_truck_999/assets/143490860/e1caf455-715d-4753-a0fd-835ef399c1ce)

3.Hardware setting (HC-SR04)
![image](https://github.com/Intel-Edge-AI-SW-Developers-2nd-Platoon/platooning_bando_truck_999/assets/143490860/6e8946f0-8e24-4733-b2e0-a210f0c24c7d)

The description and photos below show how to set up a project that combines two sensors.

4.MX setting

- GPIO

![sonicgpio](https://github.com/Intel-Edge-AI-SW-Developers-2nd-Platoon/platooning_bando_truck_999/assets/143490860/53cc230d-435c-441d-8484-a7a3bde1d99f)

- TIM3

![timer](https://github.com/Intel-Edge-AI-SW-Developers-2nd-Platoon/platooning_bando_truck_999/assets/143490860/1492ddea-3899-467f-b09d-0d3bf5612636)

- ADC setup

![adc_set](https://github.com/Intel-Edge-AI-SW-Developers-2nd-Platoon/platooning_bando_truck_999/assets/143490860/20222e49-401e-4173-8aee-c19a6861491d)

- ADC

![ADC](https://github.com/Intel-Edge-AI-SW-Developers-2nd-Platoon/platooning_bando_truck_999/assets/143490860/13755c5c-12a3-4881-8ed1-a64f86dd3a25)

-NVIC

![nvic](https://github.com/Intel-Edge-AI-SW-Developers-2nd-Platoon/platooning_bando_truck_999/assets/143490860/5049075b-f5db-41ef-ab1c-edd47ccd89ed)

TIM2 ADC1/2/3  USART3 Interrupt Enabled.

5.ADC calculate 
ADC value - To calculate the distance, the equation was calculated by actually measuring based on the graph shown in the data sheet and saving it in an Excel table.

![excel](https://github.com/Intel-Edge-AI-SW-Developers-2nd-Platoon/platooning_bando_truck_999/assets/143490860/44a3a16d-9851-4b7a-89bc-e6cc401f75f5)

**Comment by roby238** [comment]
Good
