### ISSUE TITLE
feat: Interface UART on ECI

### ISSUE THREAD

**Issue by User3198352** [Intel-Edge-AI-SW-Developers-2nd-Platoon/platooning_bando_truck_999#17]
Details:

1. Target board: STM32F103C8T6

2. MX setting

- UART
![ECU_UART_setting](https://github.com/Intel-Edge-AI-SW-Developers-2nd-Platoon/platooning_bando_truck_999/assets/147671780/b90734bb-9106-4c89-b6c3-ac1aa76572ad)

- NVIC
![ECU_NVIC_setting](https://github.com/Intel-Edge-AI-SW-Developers-2nd-Platoon/platooning_bando_truck_999/assets/147671780/9f497db6-c52d-4fae-8b6e-2bff0bc64e6f)

**Comment by roby238** [comment]
OK
